service:
  name: clean-architecture-serverless-typescript

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 1

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(serverless/env.yml):${self:provider.stage}}
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - { 'Fn::GetAtt': ['DynamoDbTablePerson', 'Arn'] }
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.PERSON_TABLE_NAME}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  - ${file(serverless/resources/aws-dynamodb-person-table.yml)}
